### ISSUE TITLE
markdown output

### ISSUE THREAD

**Issue by rusintez** [djadmin/medium-cli#1]

**Comment by djadmin** [comment]
That would be nice to have, but should be made as an optional feature IMHO. Not sure, how many would be comfortable reading markdown.

**Comment by rusintez** [comment]
markdown view + chalk markdown could make reading from terminal more legible

**Comment by rusintez** [comment]
... working on html to markdown pull request

**Comment by IonicaBizau** [comment]
@djadmin This project is great! ✨ 

To visualize the markdown content in terminal I created [`mdy`](https://github.com/IonicaBizau/mdy) which also ASCII-fies the images. 😁

**Comment by djadmin** [comment]
That's so cool @IonicaBizau. I'm gonna try it right away.

**Comment by djadmin** [comment]
Medium CLI v1.4.0 has markdown output support. Thanks to @churchs19.
