### ISSUE TITLE
npm version is not latest

### ISSUE THREAD

**Issue by greg-js** [djadmin/medium-cli#14]
Hi ;-)

I was just writing a quick blog post about your nice project and I noticed you forgot to push v`1.3.2` to npm. At least I think so, as I'm unable to fetch the latest version from the npm registry and it shows the last version there is v`1.3.1`

**Comment by djadmin** [comment]
Hey :)
I've pushed the latest version on npm (v1.3.2).
Awesome. Looking forward to your blog post. 😃
