### ISSUE TITLE
Filter by 'Tag'

### ISSUE THREAD

**Issue by StewartJarod** [djadmin/medium-cli#2]
On Medium you can search by tags: 'https://medium.com/tag/startups'

Create an option to search by tags. example usage: `medium --tag (-t) startups` 

Or change `medium top` and `medium open` to `--top` || `-t` `--open` || `-o` `-b` `--browser` and then allow search of tags like so: `medium startups` `medium productivity`

Definitely open to feedback on how this should work or how you would like it to work.

**Comment by djadmin** [comment]
Adding filter by 'Tag' is definitely a Great Idea, I'll try to add in the next release. Pull requests are welcome! :)

**Comment by djadmin** [comment]
Now, you can filter by Tag & Author. Big Thanks to @greg-js.
